# https://pre-commit.com/
exclude: '0\S' # исключение миграций. Т.к. есть проблема с неправильными правама на файл

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-merge-conflict
      - id: check-ast

  - repo: https://github.com/jorisroovers/gitlint
    rev:  v0.19.1
    hooks:
      - id: gitlint


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [ --fix ]
        pass_filenames: false
      - id: ruff-format
        args: [ --config=backend/pyproject.toml ]
