# Generated by Django 4.2.13 on 2024-06-25 07:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='HotelSuite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('type', models.IntegerField(choices=[(0, 'Standard'), (1, 'Superior room'), (2, 'Apartment'), (3, 'Luxe'), (4, 'Two floors')], default=0, verbose_name='Тип')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Номер в отеле',
                'verbose_name_plural': 'Номера в отеле',
            },
        ),
    ]
